### ISSUE TITLE
[ECOSYSTEM CHALLENGE] Using Remix and MetaMask on Moonbeam

### ISSUE THREAD

**Issue by albertov19** [Joshglobal/Hello-Polkadot-2020#2]
Hi Joshglobal,

Thanks for your submission. Please note that the answer is only the address of the checkContract. We have an automated script that verifies that your submission is correct, but for that we need the checkContract address.

Regards
Alberto

**Comment by Joshglobal** [comment]
Hi Albertov19 

Thank you for letting me know. I deployed a new checkContract address and updated the submission. Thank you for your help.

**Comment by albertov19** [comment]
Hey Josh,

You still need to approve the spender that is specified in the instructions.

Regards
Alberto
